Fatal error: exception Failure("Name x already defined in scope")
