Fatal error: exception Failure("Function foo already defined")
