Fatal error: exception Failure("enum with name e already defined")
